const CARS = [
  // --- SPORT ---
  {
    id: "1",
    img: "/images/sport_cars_img/mc20.png",
    hdr: "Maserati",
    subt: "MC20",
    type: "sport",
    /* */
    imgHero: "/images/HeroCars/mc20.png",
    imgSec: "/images/articleCars/mc20article.jpg",
    /* */
    desc: "The Maserati MC20 is a pure expression of Italian performance and design. With its lightweight carbon-fiber structure and race-bred V6 engine, it delivers breathtaking acceleration and precision handling. A true supercar crafted for those who demand both beauty and speed.",
    param: [
      "2023",
      "630 HP",
      "325 km/h",
      "2",
      "3.0L twin-turbo V6 Nettuno",
      "8-speed dual-clutch automatic",
    ],
    equip: [
      "Carbon-fiber monocoque chassis",
      "adaptive suspension",
      "Brembo carbon-ceramic brakes",
      "10.25-inch touchscreen",
      "premium Sonus Faber audio",
      "drive mode selector (GT, Sport, Corsa)",
      "butterfly doors",
      "rearview camera",
      "launch control system",
    ],
    prices: [
      "€1,700",
      "€1,600/day",
      "€1,500/day",
      "€1,400/day",
      "€1,300/day",
      "€7/km",
      "€12,000",
    ],
  },
  {
    id: "2",
    img: "/images/sport_cars_img/m4.png",
    hdr: "BMW",
    subt: "M4",
    type: "sport",
    /* */
    imgHero: "/images/HeroCars/m4.png",
    imgSec: "/images/articleCars/m4article.jpg",
    /* */
    desc: "The BMW M4 combines everyday usability with motorsport DNA. With aggressive styling, precise handling, and a twin-turbocharged straight-six engine, it delivers a thrilling drive that blends speed and control like no other.",
    param: [
      "2023",
      "510 HP",
      "290 km/h",
      "4",
      "3.0L inline-6 twin-turbo",
      "8-speed M Steptronic automatic",
    ],
    equip: [
      "M xDrive all-wheel drive",
      "adaptive M suspension",
      "M carbon bucket seats",
      "Harman Kardon surround sound",
      "12.3-inch Live Cockpit Professional",
      "head-up display",
      "carbon-fiber interior trim",
      "wireless Apple CarPlay/Android Auto",
      "parking sensors and camera",
    ],
    prices: [
      "€900",
      "€850/day",
      "€800/day",
      "€750/day",
      "€700/day",
      "€4/km",
      "€6,000",
    ],
  },
  {
    id: "3",
    img: "/images/sport_cars_img/taycan.png",
    hdr: "Porsche",
    subt: "Taycan",
    type: "sport",
    /**/
    imgHero: "/images/HeroCars/taycan.png",
    imgSec: "/images/articleCars/taycanarticle.jpg",
    /**/
    desc: "The Porsche Taycan is the future of sports cars. Fully electric, it combines Porsche’s iconic driving dynamics with cutting-edge technology. Instant torque, futuristic design, and luxurious comfort make every journey both thrilling and sustainable.",
    param: [
      "2023",
      "680 HP",
      "260 km/h",
      "4",
      "Electric (93.4 kWh battery)",
      "2-speed automatic (rear axle)",
    ],
    equip: [
      "All-wheel drive",
      "adaptive air suspension",
      "Porsche Active Aerodynamics",
      "16.8-inch curved display",
      "BOSE surround system",
      "800-volt fast charging",
      "panoramic fixed glass roof",
      "4-zone climate control",
      "Porsche Connect with Apple CarPlay",
    ],
    prices: [
      "€1,000",
      "€950/day",
      "€900/day",
      "€850/day",
      "€800/day",
      "€5/km",
      "€7,500",
    ],
  },
  {
    id: "4",
    img: "/images/sport_cars_img/huracan.png",
    hdr: "Lamborghini",
    subt: "Huracán EVO",
    type: "sport",
    /**/
    imgHero: "/images/HeroCars/huracan.png",
    imgSec: "/images/articleCars/huracanarticle.jpg",
    /**/
    desc: "The Lamborghini Huracán EVO is a masterpiece of performance and design. With its roaring V10 engine, razor-sharp aerodynamics, and state-of-the-art LDVI system, it delivers an unparalleled driving experience where speed, innovation, and pure adrenaline meet.",
    param: [
      "2023",
      "640 HP",
      "325 km/h",
      "2",
      "5.2L V10 naturally aspirated",
      "7-speed dual-clutch automatic",
    ],
    equip: [
      "All-wheel drive with torque vectoring",
      "20-inch Aesir rims",
      "Pirelli P Zero tires",
      "LED headlights and taillights",
      "8.4-inch touchscreen",
      "Apple CarPlay",
      "LDVI dynamic handling system",
      "carbon-ceramic brakes",
      "rearview camera",
      "parking sensors",
    ],
    prices: [
      "€1,600",
      "€1,500/day",
      "€1,400/day",
      "€1,300/day",
      "€1,200/day",
      "€6/km",
      "€11,000",
    ],
  },
  {
    id: "5",
    img: "/images/sport_cars_img/supra.png",
    hdr: "Toyota",
    subt: "Supra",
    type: "sport",
    /**/
    imgHero: "/images/HeroCars/supra.png",
    imgSec: "/images/articleCars/supraarticle.jpg",
    /**/
    desc: "The Toyota GR Supra is a legend reborn. With its turbocharged inline-six engine, rear-wheel-drive balance, and unmistakable design, it delivers a thrilling drive that pays homage to its iconic heritage while embracing modern performance.",
    param: [
      "2023",
      "340 HP",
      "250 km/h",
      "2",
      "3.0L inline-6 turbo",
      "8-speed automatic",
    ],
    equip: [
      "Rear-wheel drive",
      "adaptive suspension",
      "sports seats with Alcantara",
      "8.8-inch infotainment touchscreen",
      "JBL premium sound system",
      "Apple CarPlay",
      "adaptive cruise control",
      "Brembo brakes",
      "LED headlights",
      "rearview camera",
    ],
    prices: [
      "€700",
      "€650/day",
      "€600/day",
      "€550/day",
      "€500/day",
      "€3/km",
      "€4,500",
    ],
  },
  {
    id: "6",
    img: "/images/sport_cars_img/mustang.png",
    hdr: "Ford",
    subt: "Mustang",
    type: "sport",
    /**/
    imgHero: "/images/HeroCars/mustang.png",
    imgSec: "/images/articleCars/mustangarticle.jpg",
    /**/
    desc: "The Ford Mustang is an American icon, combining muscle-car heritage with modern performance. With its thundering V8 engine and bold design, it delivers raw power, freedom, and excitement on every road.",
    param: [
      "2023",
      "450 HP",
      "250 km/h",
      "4",
      "5.0L V8 naturally aspirated",
      "10-speed automatic",
    ],
    equip: [
      "Rear-wheel drive",
      "MagneRide adaptive suspension",
      "12-inch digital cluster",
      "Bang & Olufsen premium sound",
      "leather-trimmed sport seats",
      "Apple CarPlay & Android Auto",
      "launch control",
      "Brembo brakes",
      "LED headlights",
    ],
    prices: [
      "€650",
      "€600/day",
      "€550/day",
      "€500/day",
      "€450/day",
      "€3/km",
      "€4,000",
    ],
  },
  {
    id: "7",
    img: "/images/sport_cars_img/chiron.png",
    hdr: "Bugatti",
    subt: "Chiron",
    type: "sport",
    /**/
    imgHero: "/images/HeroCars/chiron.png",
    imgSec: "/images/articleCars/chironarticle.jpg",
    /**/
    desc: "The Bugatti Chiron is the ultimate hypercar, pushing the boundaries of speed, engineering, and luxury. With a quad-turbocharged W16 engine delivering unprecedented power, it is more than a car – it is an icon of automotive excellence.",
    param: [
      "2023",
      "1,500 HP",
      "420 km/h",
      "2",
      "8.0L quad-turbo W16",
      "7-speed dual-clutch automatic",
    ],
    equip: [
      "All-wheel drive",
      "carbon-fiber body",
      "adaptive suspension",
      "bespoke leather interior",
      "12-inch infotainment display",
      "premium sound system",
      "active aerodynamics",
      "carbon-ceramic brakes",
      "launch control",
      "advanced telemetry system",
    ],
    prices: [
      "€15,000",
      "€14,000/day",
      "€13,000/day",
      "€12,000/day",
      "€11,000/day",
      "€25/km",
      "€100,000",
    ],
  },
  {
    id: "8",
    img: "/images/sport_cars_img/corvette.png",
    hdr: "Chevrolet",
    subt: "Corvette Z06",
    type: "sport",
    /**/
    imgHero: "/images/HeroCars/corvette.png",
    imgSec: "/images/articleCars/corvettearticle.jpg",
    /**/
    desc: "The Chevrolet Corvette Z06 is America’s supercar, built for track dominance and road presence. With its naturally aspirated V8, aggressive aerodynamics, and precision engineering, it delivers adrenaline-fueled performance at every turn.",
    param: [
      "2023",
      "670 HP",
      "315 km/h",
      "2",
      "5.5L V8 naturally aspirated",
      "8-speed dual-clutch automatic",
    ],
    equip: [
      "Rear-wheel drive",
      "carbon-fiber aero package",
      "Magnetic Ride Control",
      "8-inch touchscreen with Apple CarPlay/Android Auto",
      "Bose Performance audio",
      "competition sport seats",
      "Brembo carbon-ceramic brakes",
      "head-up display",
      "launch control system",
    ],
    prices: [
      "€1,200",
      "€1,100/day",
      "€1,000/day",
      "€950/day",
      "€900/day",
      "€6/km",
      "€8,000",
    ],
  },

  // --- LUXURY ---
  {
    id: "9",
    img: "/images/luxury_cars_img/classes.png",
    hdr: "Mercedes-Benz",
    subt: "Maybach Classe S",
    type: "luxury",
    /**/
    imgHero: "/images/HeroCars/classes.png",
    imgSec: "/images/articleCars/classesarticle.jpg",
    /**/
    desc: "The Mercedes-Maybach S-Class is the pinnacle of luxury and sophistication. With handcrafted refinement, advanced technology, and unmatched comfort, it transforms every drive into an experience of pure prestige. From its elegant silhouette to its serene cabin, the Maybach is a statement of excellence.",
    param: [
      "2023",
      "496 HP",
      "250 km/h",
      "4–5",
      "4.0L V8 Biturbo",
      "9-speed automatic",
    ],
    equip: [
      "All-wheel drive (4MATIC)",
      "adaptive air suspension",
      "executive rear seating with massage and ventilation",
      "Burmester 4D surround sound system",
      "12.8-inch OLED central display",
      "MBUX infotainment with voice control",
      "panoramic sunroof",
      "ambient lighting with 64 colors",
      "rear-seat entertainment",
      "advanced driver assistance systems",
    ],
    prices: [
      "€1,200",
      "€1,100/day",
      "€1,000/day",
      "€900/day",
      "€800/day",
      "€5/km",
      "€10,000",
    ],
  },
  {
    id: "10",
    img: "/images/luxury_cars_img/i7.png",
    hdr: "BMW",
    subt: "i7",
    type: "luxury",
    /**/
    imgHero: "/images/HeroCars/i7.png",
    imgSec: "/images/articleCars/i7article.jpg",
    /**/
    desc: "The BMW i7 redefines luxury mobility with its all-electric performance and cutting-edge design. Combining silent power, state-of-the-art technology, and a lounge-like interior, it offers an experience that is both sustainable and breathtaking. Innovation and elegance meet in every journey.",
    param: [
      "2023",
      "544 HP",
      "240 km/h",
      "5",
      "Electric (101.7 kWh battery)",
      "Single-speed automatic",
    ],
    equip: [
      "xDrive all-wheel drive",
      "31.3-inch BMW Theatre Screen with 8K resolution",
      "Bowers & Wilkins Diamond Surround Sound",
      "crystal glass interior elements",
      "14.9-inch curved display",
      "gesture control",
      "panoramic Sky Lounge roof",
      "adaptive air suspension",
      "Level 2 driver assistance",
      "four-zone climate control",
    ],
    prices: [
      "€1,000",
      "€900/day",
      "€850/day",
      "€800/day",
      "€750/day",
      "€5/km",
      "€9,000",
    ],
  },
  {
    id: "11",
    img: "/images/luxury_cars_img/classec.png",
    hdr: "Mercedes-Benz",
    subt: "Classe C",
    type: "luxury",
    /**/
    imgHero: "/images/HeroCars/classec.png",
    imgSec: "/images/articleCars/classecarticle.jpg",
    /**/
    desc: "The Mercedes-Benz C-Class combines sportiness and elegance with refined comfort. With advanced driving technologies, premium design, and dynamic handling, it embodies the essence of modern luxury in a compact form. Perfectly balanced for city and highway drives alike.",
    param: [
      "2018",
      "258 HP",
      "250 km/h",
      "5",
      "2.0L inline-4 turbo",
      "9-speed automatic",
    ],
    equip: [
      "Rear-wheel drive with optional 4MATIC",
      "AMG Line exterior package",
      "LED headlights and taillights",
      "12.3-inch digital cockpit",
      "MBUX infotainment system with voice assistant",
      "Burmester surround sound",
      "panoramic sunroof",
      "wireless charging",
      "adaptive cruise control",
      "parking sensors with 360° camera",
    ],
    prices: [
      "€600",
      "€550/day",
      "€500/day",
      "€450/day",
      "€400/day",
      "€3/km",
      "€5,000",
    ],
  },
  {
    id: "12",
    img: "/images/luxury_cars_img/cle.png",
    hdr: "Mercedes-Benz",
    subt: "CLE Cabriolet",
    type: "luxury",
    /**/
    imgHero: "/images/HeroCars/cle.png",
    imgSec: "/images/articleCars/clearticle.jpg",
    /**/
    desc: "The Mercedes-Benz CLE Cabriolet is the epitome of open-air elegance. With its sleek design, powerful engines, and luxury appointments, it offers an exhilarating drive beneath the sky. Every detail reflects sophistication, freedom, and pure joy of driving.",
    param: [
      "2024",
      "381 HP",
      "250 km/h",
      "4",
      "3.0L inline-6 turbo mild hybrid",
      "9-speed automatic",
    ],
    equip: [
      "Cabriolet soft-top with acoustic insulation",
      "4MATIC all-wheel drive",
      "AMG Line styling",
      "12.3-inch driver display",
      "11.9-inch central touchscreen",
      "Burmester 3D surround sound",
      "AIRSCARF neck-level heating",
      "adaptive suspension",
      "ambient lighting",
      "driver assistance package",
    ],
    prices: [
      "€800",
      "€750/day",
      "€700/day",
      "€650/day",
      "€600/day",
      "€4/km",
      "€7,000",
    ],
  },
  {
    id: "13",
    img: "/images/luxury_cars_img/ghost.png",
    hdr: "Rolls-Royce",
    subt: "Ghost",
    type: "luxury",
    /**/
    imgHero: "/images/HeroCars/ghost.png",
    imgSec: "/images/articleCars/ghostarticle.jpg",
    /**/
    desc: "The Rolls-Royce Ghost embodies timeless elegance and effortless power. With a whisper-quiet V12 engine, unmatched craftsmanship, and a sanctuary-like interior, it transforms every journey into a serene masterpiece of luxury. A true icon of prestige.",
    param: [
      "2023",
      "571 HP",
      "250 km/h",
      "4–5",
      "6.75L V12 twin-turbo",
      "8-speed automatic",
    ],
    equip: [
      "All-wheel drive",
      "adaptive suspension with Flagbearer system",
      "Starlight Headliner",
      "bespoke leather interior",
      "18-speaker Bespoke Audio system",
      "12.3-inch infotainment screen",
      "rear-seat entertainment",
      "soft-close doors",
      "massage seats",
      "advanced driver assistance features",
    ],
    prices: [
      "€1,800",
      "€1,700/day",
      "€1,600/day",
      "€1,500/day",
      "€1,400/day",
      "€8/km",
      "€15,000",
    ],
  },
  {
    id: "14",
    img: "/images/luxury_cars_img/spur.png",
    hdr: "Bentley",
    subt: "Flying Spur",
    type: "luxury",
    /**/
    imgHero: "/images/HeroCars/spur.png",
    imgSec: "/images/articleCars/spurarticle.jpg",
    /**/
    desc: "The Bentley Flying Spur is a seamless fusion of performance and luxury. With a commanding W12 engine, exquisite handcrafted interior, and cutting-edge technology, it offers an extraordinary driving experience that blends speed, comfort, and prestige in perfect harmony.",
    param: [
      "2023",
      "635 HP",
      "333 km/h",
      "4–5",
      "6.0L W12 twin-turbo",
      "8-speed dual-clutch automatic",
    ],
    equip: [
      "All-wheel drive",
      "adaptive air suspension",
      "Mulliner interior detailing",
      "12.3-inch rotating display",
      "Bang & Olufsen premium sound system",
      "panoramic sunroof",
      "heated and ventilated seats",
      "rear-seat entertainment",
      "driver assistance package",
      "carbon-ceramic brakes",
    ],
    prices: [
      "€1,500",
      "€1,400/day",
      "€1,300/day",
      "€1,200/day",
      "€1,100/day",
      "€7/km",
      "€12,000",
    ],
  },

  // --- SUV ---
  {
    id: "15",
    img: "/images/suv_img/cullinan.png",
    hdr: "Rolls-Royce",
    subt: "Cullinan",
    type: "SUV",
    /**/
    imgHero: "/images/HeroCars/cullinan.png",
    imgSec: "/images/articleCars/cullinanarticle.jpg",
    /**/
    desc: "The Rolls-Royce Cullinan redefines the luxury SUV. Combining unrivaled craftsmanship with commanding presence and effortless performance, it offers a sanctuary of comfort and prestige both in the city and on any terrain. A true symbol of refined adventure.",
    param: [
      "2023",
      "571 HP",
      "250 km/h",
      "5",
      "6.75L V12 twin-turbo",
      "8-speed automatic",
    ],
    equip: [
      "All-wheel drive",
      "adaptive air suspension",
      "Starlight Headliner",
      "bespoke leather interior",
      "rear-seat entertainment screens",
      "panoramic sunroof",
      "18-speaker Bespoke Audio",
      "soft-close doors",
      "massage seats",
      "advanced driver assistance systems",
    ],
    prices: [
      "€2,000",
      "€1,900/day",
      "€1,800/day",
      "€1,700/day",
      "€1,600/day",
      "€9/km",
      "€18,000",
    ],
  },
  {
    id: "16",
    img: "/images/suv_img/urus.png",
    hdr: "Lamborghini",
    subt: "Urus",
    type: "SUV",
    /**/
    imgHero: "/images/HeroCars/urus.png",
    imgSec: "/images/articleCars/urusarticle.jpg",
    /**/
    desc: "The Lamborghini Urus is the world’s first Super SUV, combining supercar performance with everyday practicality. With its powerful V8, cutting-edge design, and commanding presence, it turns every journey into an extraordinary adventure.",
    param: [
      "2023",
      "650 HP",
      "305 km/h",
      "5",
      "4.0L V8 twin-turbo",
      "8-speed automatic",
    ],
    equip: [
      "All-wheel drive with torque vectoring",
      "adaptive air suspension",
      "21-inch alloy wheels",
      "Pirelli P Zero tires",
      "12.3-inch infotainment touchscreen",
      "Bang & Olufsen 3D audio",
      "carbon-ceramic brakes",
      "ambient lighting",
      "rearview camera",
      "parking sensors",
    ],
    prices: [
      "€1,500",
      "€1,400/day",
      "€1,300/day",
      "€1,200/day",
      "€1,100/day",
      "€7/km",
      "€12,000",
    ],
  },
  {
    id: "17",
    img: "/images/suv_img/cayenne.png",
    hdr: "Porsche",
    subt: "Cayenne",
    type: "SUV",
    /**/
    imgHero: "/images/HeroCars/cayenne.png",
    imgSec: "/images/articleCars/cayennearticle.jpg",
    /**/
    desc: "The Porsche Cayenne blends sports-car DNA with SUV versatility. Dynamic, elegant, and powerful, it delivers thrilling performance alongside everyday comfort, making it one of the most iconic luxury SUVs in the world.",
    param: [
      "2023",
      "470 HP",
      "270 km/h",
      "5",
      "4.0L V8 twin-turbo",
      "8-speed Tiptronic automatic",
    ],
    equip: [
      "Porsche Active Suspension Management",
      "adaptive cruise control",
      "BOSE surround sound",
      "12.3-inch Porsche Communication Management display",
      "Sport Chrono package",
      "panoramic roof",
      "leather interior",
      "LED matrix headlights",
      "rearview camera",
    ],
    prices: [
      "€1,000",
      "€950/day",
      "€900/day",
      "€850/day",
      "€800/day",
      "€5/km",
      "€8,500",
    ],
  },
  {
    id: "18",
    img: "/images/suv_img/gle.png",
    hdr: "Mercedes-Benz",
    subt: "GLE Coupe 450d",
    type: "SUV",
    /**/
    imgHero: "/images/HeroCars/gle.png",
    imgSec: "/images/articleCars/glearticle.jpg",
    /**/
    desc: "The Mercedes-Benz GLE Coupe 450d combines sporty elegance with SUV power. With its sleek coupe silhouette, advanced diesel engine, and luxurious interior, it offers the perfect balance of performance, comfort, and style.",
    param: [
      "2023",
      "367 HP + 20 HP EQ Boost",
      "250 km/h",
      "5",
      "3.0L inline-6 diesel mild hybrid",
      "9-speed automatic",
    ],
    equip: [
      "4MATIC all-wheel drive",
      "AMG Line exterior",
      "adaptive suspension",
      "MBUX infotainment with voice assistant",
      "Burmester surround sound",
      "12.3-inch digital cockpit",
      "panoramic sunroof",
      "heated and ventilated seats",
      "driver assistance package",
      "parking sensors",
    ],
    prices: [
      "€850",
      "€800/day",
      "€750/day",
      "€700/day",
      "€650/day",
      "€4/km",
      "€6,500",
    ],
  },
  {
    id: "19",
    img: "/images/suv_img/q5.png",
    hdr: "Audi",
    subt: "Q5",
    type: "SUV",
    /**/
    imgHero: "/images/HeroCars/q5.png",
    imgSec: "/images/articleCars/q5article.jpg",
    /**/
    desc: "The Audi Q5 is a premium SUV that blends efficiency, comfort, and technology. With its sleek design, quattro all-wheel drive, and refined interior, it delivers a versatile driving experience for both city streets and open roads.",
    param: [
      "2023",
      "265 HP",
      "240 km/h",
      "5",
      "2.0L TFSI turbo",
      "7-speed S tronic automatic",
    ],
    equip: [
      "Quattro all-wheel drive",
      "virtual cockpit",
      "MMI navigation plus with 10.1-inch touchscreen",
      "Bang & Olufsen 3D audio",
      "adaptive cruise assist",
      "panoramic sunroof",
      "leather interior",
      "LED headlights",
      "rearview camera",
      "parking sensors",
    ],
    prices: [
      "€600",
      "€550/day",
      "€500/day",
      "€450/day",
      "€400/day",
      "€3/km",
      "€4,000",
    ],
  },
  {
    id: "20",
    img: "/images/suv_img/classeg.png",
    hdr: "Mercedes-Benz",
    subt: "Classe G",
    type: "SUV",
    /**/
    imgHero: "/images/HeroCars/classeg.png",
    imgSec: "/images/articleCars/classegarticle.jpg",
    /**/
    desc: "The Mercedes-Benz G-Class is an icon of strength and prestige. With its unmistakable design, legendary off-road capability, and ultra-luxurious interior, it delivers uncompromising performance both on rugged trails and city boulevards.",
    param: [
      "2023",
      "585 HP",
      "240 km/h",
      "5",
      "4.0L V8 biturbo",
      "9-speed automatic",
    ],
    equip: [
      "AMG Performance 4MATIC all-wheel drive",
      "adaptive suspension",
      "Nappa leather interior",
      "Burmester surround sound",
      "12.3-inch dual-screen cockpit",
      "ambient lighting",
      "panoramic sunroof",
      "off-road driving modes",
      "carbon-fiber trim",
      "rearview camera",
    ],
    prices: [
      "€1,400",
      "€1,300/day",
      "€1,200/day",
      "€1,100/day",
      "€1,000/day",
      "€6/km",
      "€10,000",
    ],
  },
];

export default CARS;
